FROM golang:1.25-alpine

RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app
COPY services/manager/go.mod services/manager/go.sum ./
RUN go mod download
COPY services/manager/ ./

EXPOSE 8081 9090
CMD ["air", "-c", ".air.toml"]
