FROM golang:1.22-alpine

RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app
COPY services/gateway/go.mod services/gateway/go.sum ./
RUN go mod download
COPY services/gateway/ ./

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
